In [1]:
import pandas as pd
import numpy as np

data = pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Delinquency\Delinquency_Cleaned_Data.xlsx")
data.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580,398,0.390502,3,0,16310,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999,493,0.312444,6,1,17401,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416,500,0.359930,0,0,13761,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672,413,0.371400,3,0,88778,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524,487,0.234716,2,0,13316,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                500 non-null    object
 3   Credit_Score          500 non-null    int64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          500 non-null    int64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(2), int64(6), object(11)
memory usage: 74.3+ KB

In [3]:
total_month = 6
data['Delinquency_Rate'] = data['Missed_Payments'] / total_month

In [4]:
data.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6,Delinquency_Rate
0,CUST0001,56,165580,398,0.390502,3,0,16310,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late,0.500000
1,CUST0002,69,100999,493,0.312444,6,1,17401,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time,1.000000
2,CUST0003,46,188416,500,0.359930,0,0,13761,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late,0.000000
3,CUST0004,32,101672,413,0.371400,3,0,88778,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late,0.500000
4,CUST0005,60,38524,487,0.234716,2,0,13316,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late,0.333333

In [5]:
def delinquency_band(rate):
    if rate <= 0.16:
        return 'Low'
    elif rate<= 0.33:
        return 'Medium'
    else:
        return 'HIgh'
data['Delinquency_Risk_Band'] = data['Delinquency_Rate'].apply(delinquency_band)

In [6]:
data['Delinquency_Risk_Band'].tail()

495      HIgh
496      HIgh
497       Low
498      HIgh
499    Medium
Name: Delinquency_Risk_Band, dtype: object

In [7]:
# High Credit Utilization Flag
data['High_Utilization_Flag'] = (data['Credit_Utilization'] > 0.30).astype(int)

In [8]:
# High DTI Flag
data['High_DTI_Flag'] = (data['Debt_to_Income_Ratio'] > 0.40).astype(int)
data.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,...,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6,Delinquency_Rate,Delinquency_Risk_Band,High_Utilization_Flag,High_DTI_Flag
0,CUST0001,56,165580,398,0.390502,3,0,16310,0.317396,EMP,...,Late,Late,Missed,Late,Missed,Late,0.500000,HIgh,1,0
1,CUST0002,69,100999,493,0.312444,6,1,17401,0.196093,Self-employed,...,Missed,Missed,Late,Missed,On-time,On-time,1.000000,HIgh,1,0
2,CUST0003,46,188416,500,0.359930,0,0,13761,0.301655,Self-employed,...,Missed,Late,Late,On-time,Missed,Late,0.000000,Low,1,0
3,CUST0004,32,101672,413,0.371400,3,0,88778,0.264794,Unemployed,...,Late,Missed,Late,Missed,Late,Late,0.500000,HIgh,1,0
4,CUST0005,60,38524,487,0.234716,2,0,13316,0.510583,Self-employed,...,Missed,On-time,Missed,Late,Late,Late,0.333333,HIgh,0,1

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            500 non-null    object
 1   Age                    500 non-null    int64
 2   Income                 500 non-null    object
 3   Credit_Score           500 non-null    int64
 4   Credit_Utilization     500 non-null    float64
 5   Missed_Payments        500 non-null    int64
 6   Delinquent_Account     500 non-null    int64
 7   Loan_Balance           500 non-null    int64
 8   Debt_to_Income_Ratio   500 non-null    float64
 9   Employment_Status      500 non-null    object
 10  Account_Tenure         500 non-null    int64
 11  Credit_Card_Type       500 non-null    object
 12  Location               500 non-null    object
 13  Month_1                500 non-null    object
 14  Month_2                500 non-null    object
 15  Month_3                500 non-null    object
 16  Month_4                500 non-null    object
 17  Month_5                500 non-null    object
 18  Month_6                500 non-null    object
 19  Delinquency_Rate       500 non-null    float64
 20  Delinquency_Risk_Band  500 non-null    object
 21  High_Utilization_Flag  500 non-null    int64
 22  High_DTI_Flag          500 non-null    int64
dtypes: float64(3), int64(8), object(12)
memory usage: 90.0+ KB

In [10]:
def loan_size_bucket(balance):
    if balance <= 200000:
        return 'Small'
    elif balance <= 500000:
        return 'Medium'
    else:
        return 'Large'

data['Loan_Size'] = data['Loan_Balance'].apply(loan_size_bucket)

In [11]:
data.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,...,Month_2,Month_3,Month_4,Month_5,Month_6,Delinquency_Rate,Delinquency_Risk_Band,High_Utilization_Flag,High_DTI_Flag,Loan_Size
0,CUST0001,56,165580,398,0.390502,3,0,16310,0.317396,EMP,...,Late,Missed,Late,Missed,Late,0.500000,HIgh,1,0,Small
1,CUST0002,69,100999,493,0.312444,6,1,17401,0.196093,Self-employed,...,Missed,Late,Missed,On-time,On-time,1.000000,HIgh,1,0,Small
2,CUST0003,46,188416,500,0.359930,0,0,13761,0.301655,Self-employed,...,Late,Late,On-time,Missed,Late,0.000000,Low,1,0,Small
3,CUST0004,32,101672,413,0.371400,3,0,88778,0.264794,Unemployed,...,Missed,Late,Missed,Late,Late,0.500000,HIgh,1,0,Small
4,CUST0005,60,38524,487,0.234716,2,0,13316,0.510583,Self-employed,...,On-time,Missed,Late,Late,Late,0.333333,HIgh,0,1,Small

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            500 non-null    object
 1   Age                    500 non-null    int64
 2   Income                 500 non-null    object
 3   Credit_Score           500 non-null    int64
 4   Credit_Utilization     500 non-null    float64
 5   Missed_Payments        500 non-null    int64
 6   Delinquent_Account     500 non-null    int64
 7   Loan_Balance           500 non-null    int64
 8   Debt_to_Income_Ratio   500 non-null    float64
 9   Employment_Status      500 non-null    object
 10  Account_Tenure         500 non-null    int64
 11  Credit_Card_Type       500 non-null    object
 12  Location               500 non-null    object
 13  Month_1                500 non-null    object
 14  Month_2                500 non-null    object
 15  Month_3                500 non-null    object
 16  Month_4                500 non-null    object
 17  Month_5                500 non-null    object
 18  Month_6                500 non-null    object
 19  Delinquency_Rate       500 non-null    float64
 20  Delinquency_Risk_Band  500 non-null    object
 21  High_Utilization_Flag  500 non-null    int64
 22  High_DTI_Flag          500 non-null    int64
 23  Loan_Size              500 non-null    object
dtypes: float64(3), int64(8), object(13)
memory usage: 93.9+ KB

In [13]:
data.to_csv("Delinquency_data.csv")

In [30]:
data["Location"].unique()

array(['Los Angeles', 'Phoenix', 'Chicago', 'New York', 'Houston'],
      dtype=object)